Core Django/14. Middleware/Authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', views.home, name='home'),
    path('show', views.show_data, name='show'),
    path('delete/<int:pk>/', views.delete_data, name='delete'),
    path('update/<int:pk>/', views.update_data, name='update'),
    path('register/', views.register, name='register'),
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
]

Core Django/14. Middleware/testapp/models.py
from django.db import models


# Create your models here.

class Task(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Done', 'Done'),
        ('In-Progress', 'In-Progress'),
    )
    task = models.TextField()
    status = models.CharField(max_length=100, null=True, choices=STATUS)

Core Django/14. Middleware/testapp/forms.py
from django import forms
from .models import Task


class TaskCreate(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task', 'status']
        # widgets = {
        #     'task': forms.Textarea(attrs={'class':'form-control'}),
        #     'status': forms.CharField(attrs={'class':'form-control'})
        #
        # }

Core Django/14. Middleware/testapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import TaskCreate
from .models import Task
from django.core.paginator import Paginator


# Create your views here.


def home(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = TaskCreate(request.POST)

            if fm.is_valid():
                # task = fm.cleaned_data['task']
                # st = fm.cleaned_data['status']
                # reg = Task(task=task, status=st)
                # reg.save()
                fm.save()
                fm = TaskCreate()
        else:
            fm = TaskCreate()
        return render(request, 'home.html', {'form': fm})
    else:
        return redirect('/login/')


from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def show_data(request):
    data = Task.objects.all()
    task_paginator = Paginator(data, 5)
    page_num = request.GET.get('page')
    number = list(range(1, 12))
    page = task_paginator.get_page(page_num)
    return render(request, 'showdata.html', {'data': page, 'count': task_paginator.count, 'number':number})


def delete_data(request, pk):
    # if request.method == 'POST':
    t = Task.objects.get(id=pk)
    t.delete()
    return redirect('/')


def update_data(request, pk):
    if request.method == 'POST':
        pi = Task.objects.get(id=pk)
        fm = TaskCreate(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
    else:
        pi = Task.objects.get(id=pk)
        fm = TaskCreate(instance=pi)

    return render(request, 'updatetask.html', {'form': fm})


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'email': 'Email'}


def register(request):
    if request.method == "POST":
        fm = RegisterForm(request.POST)
        if fm.is_valid():
            messages.success(request, "Account Created Successfully !!!")
            fm.save()
    else:
        fm = RegisterForm()
    return render(request, 'register.html', {'form': fm})


from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fm = AuthenticationForm(request=request, data=request.POST)
            if fm.is_valid():
                uname = fm.cleaned_data['username']
                upass = fm.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in successfully !!')
                    return redirect('/show')
        else:
            fm = AuthenticationForm()
        return render(request, 'login.html', {'form': fm})
    else:
        return redirect('/show')


def user_logout(request):
    logout(request)
    return redirect('/')

Core Django/14. Middleware/testapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Task List</title>
</head>
<body>

    <div class="container mt-5">
        {% if messages %}
            {% for message in messages %}
                <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
            {% endfor %}
        {% endif %}
        <h2 class="text-center alert alert-danger">Add Task</h2>
        <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Add">
        <a href="{% url 'show' %}" class="btn btn-info">Back to Home</a>
    </form>

    </div>

</body>
</html>

Core Django/14. Middleware/testapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User login</title>
    <style> .error{color: red;}</style>
</head>
<body>
    <h3>login</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="error">{{error}}</p>
        {% endfor %}
        {% endif %}

       {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Login">
    </form>

    <a href="{% url 'register' %}">Register</a>
</body>
</html>

Core Django/14. Middleware/testapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Registration</title>
    <style>
        .success{ color: red; }
        .error{color: red;}
    </style>
</head>
<body>
    <h3>Register here</h3>

    <form action="" method="post" novalidate>
        {% csrf_token %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="error">{{error}}</p>
            {% endfor %}
        {% endif %}

        {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
        {% endfor %}

        <input type="submit" value="Submit">
    </form>

        {% if messages %}
            {% for message in messages %}
                <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
            {% endfor %}
        {% endif %}

    <a href="{% url 'login' %}">Login</a>
</body>
</html>

Core Django/14. Middleware/testapp/templates/showdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>showdata</title>
</head>
<body>

<div class="container mt-5">
{% if messages %}
        {% for message in messages %}
            <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
        {% endfor %}
    {% endif %}
    <h2 class="text-center alert alert-danger">Task Information</h2>
    <a class="btn btn-dark float-right" href="{% url 'logout' %}">Logout</a>

    {% if perms.testapp.add_task %}
    <a href="{% url 'home' %}" class="btn btn-info">Add Task</a>
    {% else %}
    <a href="" class="btn btn-info">No Add Permission</a>
    {% endif %}

    <h6>Total Number of task: {{count}}</h6>

    {% if data %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Number</th>
            <th scope="col">Task List</th>
            <th scope="col">Status</th>
            {% if perms.testapp.change_task or perms.testapp.delete_task %}
            <th scope="col">Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for d in data.object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{d.task}}</td>
            <td>{{d.status}}</td>

            <td>
                {% if perms.testapp.change_task %}
                <a href="{% url 'update' d.id %}" class="btn btn-warning btn-sm">Update</a>
                {% endif %}
                {% if perms.testapp.delete_task %}
                <a href="{% url 'delete' d.id %}" class="btn btn-danger btn-sm">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    {% else%}
    <h4>No Record</h4>
    {% endif %}
    <div class="page-links">
        <h6>Page Number: {{data.number}}</h6>
        {% if data.has_previous %}
            <a href="{% url 'show' %}?page={{data.previous_page_number}}">Previous Page</a>
        {% endif %}
        {% if data.has_next %}
            <a href="{% url 'show' %}?page={{data.next_page_number}}">Next Page</a>
        {% endif %}


    </div>

</div>
</body>
</html>

Core Django/14. Middleware/testapp/templates/updatetask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>update</title>
</head>
<body>

    <div class="container mt-5">
        <h4></h4>
            <h2 class="text-center alert alert-info">Update Task</h2>
            <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-success" value="update">

                <a href="{% url 'show' %}" class="btn btn-info">Back to Home</a>

        </form>

    </div>
</body>
</html>